Version 1.1: - Bugfix: Do not print a crc of "00000000" when there is a problem with the input file (it doesn't exist, is damaged, etc.). Instead, print an error message and exit with non-zero exit code. - Check for number of parameters and print syntax if it is not equal to 1.

diff --git a/eac-crc b/eac-crc
--- a/eac-crc
+++ b/eac-crc
@@ -1,7 +1,30 @@
 #!/bin/bash
 
 # Source & manual of this script: https://github.com/leo-bogert/eac-crc
-# Version: 1.0
+# Version: 1.1
 
-shncat -q -e "$1" | rhash --printf="%C" -
-exit $?
+compute_crc_and_preserve_shncat_exit_code() {
+	shncat -q -e "$1" | rhash --printf="%C" -
+	return ${PIPESTATUS[0]}
+}
+
+main() {
+	if [ $# -ne 1 ] ; then
+		echo "Syntax: eac-crc filename_of_input_wav" >&2
+		exit 1
+	fi
+
+	local crc	# defining & assigning it at once would overwrite $?
+	
+	crc=$(compute_crc_and_preserve_shncat_exit_code "$1")
+	
+	if [ $? -eq 0 ] ; then
+		echo "$crc"
+		exit 0
+	else
+		echo "shncat failed!" >&2
+		exit $?
+	fi
+}
+
+main "$@"
